"""adds Book model

Revision ID: 13426ea86d5d
Revises: 
Create Date: 2021-04-29 16:39:58.654063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13426ea86d5d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books_table',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('books_table')
    # ### end Alembic commands ###
